version: "3.9"

services:
  # web:
  #   build: .
  #   container_name: flask_app
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - FLASK_ENV=development
  #     - DATABASE_URL=postgresql://postgres:postgres@db:5432/flask_di_db
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/app
  #   command: flask run --host=0.0.0.0 --port=5000

  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flask_di_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
